spring:
  datasource:
    url: jdbc:mysql://localhost:3306/what_was_it?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: whatwasit
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true